name: GitHub Actions Demo
 on:
   push:
     branches:
      - main
     branches-ignore:
      - 'main/.github/**'
   pull_request:
     branches:
     - main
   schedule:
     - cron: "15 6 * * 7"
   workflow_dispatch:
     
    
      
